export const DashboardWidget = Object.freeze({
  TRAINING_PROGRESS: "TRAINING_PROGRESS",
  CERTIFICATION_STATUS: "CERTIFICATION_STATUS",
  QUALITY_INDICATORS: "QUALITY_INDICATORS",
  ANALYTICS_SUMMARY: "ANALYTICS_SUMMARY",
  PENDING_REVIEWS: "PENDING_REVIEWS",
  NOTIFICATIONS: "NOTIFICATIONS",
});
