export const InsightCategory = Object.freeze({
  LEARNING_PROGRESS: "LEARNING_PROGRESS",
  ASSESSMENT_DIFFICULTY: "ASSESSMENT_DIFFICULTY",
  CONTENT_QUALITY: "CONTENT_QUALITY",
  TRAINER_PERFORMANCE: "TRAINER_PERFORMANCE",
  LEARNER_ENGAGEMENT: "LEARNER_ENGAGEMENT",
  CERTIFICATION_RISK: "CERTIFICATION_RISK",
});
