export const RecommendationType = Object.freeze({
  CONTENT_IMPROVEMENT: "CONTENT_IMPROVEMENT",
  LEARNING_SUPPORT: "LEARNING_SUPPORT",
  TRAINING_ADJUSTMENT: "TRAINING_ADJUSTMENT",
  QUALITY_IMPROVEMENT: "QUALITY_IMPROVEMENT",
  REMINDER_SUGGESTION: "REMINDER_SUGGESTION",
  MEDIA_RECOMMENDATION: "MEDIA_RECOMMENDATION",
});
