export const UserRole = Object.freeze({
  LEARNER: "LEARNER",
  TRAINER: "TRAINER",
  TRAINING_MANAGER: "TRAINING_MANAGER",
  QUALITY_MANAGER: "QUALITY_MANAGER",
  ORGANIZATION_ADMIN: "ORGANIZATION_ADMIN",
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
});
