export const LearnerWidget = Object.freeze({
  PROGRESS_CARD: "PROGRESS_CARD",
  PATH_CARD: "PATH_CARD",
  ACTIVITY_CARD: "ACTIVITY_CARD",
  CERTIFICATE_CARD: "CERTIFICATE_CARD",
  COMPETENCY_CARD: "COMPETENCY_CARD",
  RECOMMENDATION_CARD: "RECOMMENDATION_CARD",
});
