export const QualityWidget = Object.freeze({
  SATISFACTION_CARD: "SATISFACTION_CARD",
  QUALITY_INDICATOR_CARD: "QUALITY_INDICATOR_CARD",
  TRAINER_SCORE_CARD: "TRAINER_SCORE_CARD",
  IMPROVEMENT_CARD: "IMPROVEMENT_CARD",
  AUDIT_STATUS_CARD: "AUDIT_STATUS_CARD",
  TREND_CARD: "TREND_CARD",
});
