export const NotificationTrigger = Object.freeze({
  TRAINING_REMINDER: "TRAINING_REMINDER",
  CERTIFICATION_EXPIRY_REMINDER: "CERTIFICATION_EXPIRY_REMINDER",
  WORKFLOW_NOTIFICATION: "WORKFLOW_NOTIFICATION",
  QUALITY_NOTIFICATION: "QUALITY_NOTIFICATION",
  CLIENT_COMMUNICATION: "CLIENT_COMMUNICATION",
});
