export const FeedbackCategory = Object.freeze({
  LEARNING_OBJECTIVES: "LEARNING_OBJECTIVES",
  COURSE_CONTENT: "COURSE_CONTENT",
  TRAINER: "TRAINER",
  ORGANIZATION: "ORGANIZATION",
  ADMINISTRATION: "ADMINISTRATION",
  FACILITIES: "FACILITIES",
  MATERIALS: "MATERIALS",
  ASSESSMENT: "ASSESSMENT",
  GENERAL: "GENERAL",
});
