export const SurveyType = Object.freeze({
  COURSE_SATISFACTION: "COURSE_SATISFACTION",
  TRAINER_EVALUATION: "TRAINER_EVALUATION",
  CLIENT_FEEDBACK: "CLIENT_FEEDBACK",
  SELF_ASSESSMENT: "SELF_ASSESSMENT",
});
