export const PermissionDescriptor = Object.freeze({
  VIEW_TRAINING: "VIEW_TRAINING",
  MANAGE_SESSION: "MANAGE_SESSION",
  VIEW_CERTIFICATION: "VIEW_CERTIFICATION",
  VIEW_ANALYTICS: "VIEW_ANALYTICS",
  MANAGE_QUALITY: "MANAGE_QUALITY",
  MANAGE_USERS: "MANAGE_USERS",
});
