export const DeliveryFormat = Object.freeze({
  SCORM_1_2: "SCORM_1_2",
  SCORM_2004: "SCORM_2004",
  XAPI: "XAPI",
  CMI5: "CMI5",
  IFRAME: "IFRAME",
  EMBED_SCRIPT: "EMBED_SCRIPT",
  TEAMS: "TEAMS",
  GOOGLE_CLASSROOM: "GOOGLE_CLASSROOM",
  "360LEARNING": "360LEARNING",
  MOODLE: "MOODLE",
  LMS_GENERIC: "LMS_GENERIC",
});
