export const AdminWidget = Object.freeze({
  GLOBAL_KPI: "GLOBAL_KPI",
  TRAINING_STATUS: "TRAINING_STATUS",
  CERTIFICATION_STATUS: "CERTIFICATION_STATUS",
  QUALITY_STATUS: "QUALITY_STATUS",
  USER_STATUS: "USER_STATUS",
  ALERT_LIST: "ALERT_LIST",
  ACTION_LIST: "ACTION_LIST",
});
