export const ClientWidget = Object.freeze({
  EMPLOYEE_STATUS_CARD: "EMPLOYEE_STATUS_CARD",
  TRAINING_STATUS_CARD: "TRAINING_STATUS_CARD",
  CERTIFICATION_STATUS_CARD: "CERTIFICATION_STATUS_CARD",
  COMPLIANCE_CARD: "COMPLIANCE_CARD",
  EXPIRATION_ALERT_CARD: "EXPIRATION_ALERT_CARD",
  REPORT_CARD: "REPORT_CARD",
});
