export const CourseCreationOutputType = Object.freeze({
  STRUCTURE: "STRUCTURE",
  OBJECTIVES: "OBJECTIVES",
  MODULES: "MODULES",
  ACTIVITIES: "ACTIVITIES",
  ASSESSMENT: "ASSESSMENT",
  MEDIA: "MEDIA",
});
