export const AnalyticsEventType = Object.freeze({
  TRAINING_CREATED: "TRAINING_CREATED",
  TRAINING_STARTED: "TRAINING_STARTED",
  SESSION_COMPLETED: "SESSION_COMPLETED",
  LEARNER_ENROLLED: "LEARNER_ENROLLED",
  LEARNER_COMPLETED: "LEARNER_COMPLETED",
  ASSESSMENT_COMPLETED: "ASSESSMENT_COMPLETED",
  CERTIFICATION_ISSUED: "CERTIFICATION_ISSUED",
  CERTIFICATION_EXPIRED: "CERTIFICATION_EXPIRED",
  SURVEY_COMPLETED: "SURVEY_COMPLETED",
  IMPROVEMENT_ACTION_COMPLETED: "IMPROVEMENT_ACTION_COMPLETED",
  DELIVERY_COMPLETED: "DELIVERY_COMPLETED",
});
