export const AnalyticsIndicatorType = Object.freeze({
  LEARNING_EFFECTIVENESS: "LEARNING_EFFECTIVENESS",
  TRAINING_QUALITY: "TRAINING_QUALITY",
  CERTIFICATION_COMPLIANCE: "CERTIFICATION_COMPLIANCE",
  LEARNER_ENGAGEMENT: "LEARNER_ENGAGEMENT",
  TRAINER_PERFORMANCE: "TRAINER_PERFORMANCE",
  CUSTOMER_SATISFACTION: "CUSTOMER_SATISFACTION",
});
