export const ReviewType = Object.freeze({
  PEDAGOGICAL: "PEDAGOGICAL",
  QUALITY: "QUALITY",
  TECHNICAL: "TECHNICAL",
  LEGAL: "LEGAL",
  SECURITY: "SECURITY",
  CLIENT_VALIDATION: "CLIENT_VALIDATION",
});
