export const WorkflowState = Object.freeze({
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  PEDAGOGICAL_REVIEW: "PEDAGOGICAL_REVIEW",
  QUALITY_REVIEW: "QUALITY_REVIEW",
  REVISION_REQUIRED: "REVISION_REQUIRED",
  APPROVED: "APPROVED",
  PUBLISHED: "PUBLISHED",
  ARCHIVED: "ARCHIVED",
});
