export const TrainerWidget = Object.freeze({
  TRAINING_CARD: "TRAINING_CARD",
  SESSION_CARD: "SESSION_CARD",
  LEARNER_PROGRESS_CARD: "LEARNER_PROGRESS_CARD",
  EVALUATION_CARD: "EVALUATION_CARD",
  QUALITY_CARD: "QUALITY_CARD",
  ACTION_CARD: "ACTION_CARD",
});
